### ISSUE TITLE
Read these documents ...

### ISSUE THREAD

**Issue by jdalzatec** [jdalzatec/llg#12]
Read these documents to get an idea about what we want to do.

[poster.pdf](https://github.com/jdalzatec/llg/files/3517329/poster.pdf)
[paper.pdf](https://github.com/jdalzatec/llg/files/3517330/paper.pdf)

Sign when you read :
- [x] @jdalzatec
- [x] @lufvelasquezgo 
- [x] @jussalcedoga 
- [x] @dfrodriguezp

**Comment by dfrodriguezp** [comment]
They open now, thank you!
