### ISSUE TITLE
Make  tests for the Heun scheme function

### ISSUE THREAD

**Issue by lufvelasquezgo** [jdalzatec/llg#52]

**Comment by jussalcedoga** [comment]
I think that a good test for the Heun scheme implementation would be to compare the temperature-dependent magnetization simulations for a bulk system with the analytical expression presented in the caption of Fig. 5 of **doi:10.1088/0953-8984/26/10/103202**. Also, for single spin dynamics compare the numerical solutions with the well-known analytical expressions.
