### ISSUE TITLE
Review the Python library Vapory in order to get the images in  POV-Ray.

### ISSUE THREAD

**Issue by lufvelasquezgo** [jdalzatec/llg#54]
Vapory enables to pipe the rendered images back into Python and integrates very well in the Python libraries ecosystem

[Vapory](https://pypi.org/project/Vapory/)
[Zulko](http://zulko.github.io/blog/2014/11/13/things-you-can-do-with-python-and-pov-ray/)
[Zulko - Vapory](https://github.com/Zulko/vapory)

**Comment by jdalzatec** [comment]
http://zulko.github.io/blog/2014/11/13/things-you-can-do-with-python-and-pov-ray/
