### ISSUE TITLE
Input file and output file

### ISSUE THREAD

**Issue by lufvelasquezgo** [jdalzatec/llg#55]
It would be quite nice to have an input file and an output file which contains ALL the necessary parameters which were important to do the calculations:

- input parameters (we need to choose the best format)
- interaction parameters
- spin dynamic relevant stuff

**Comment by jussalcedoga** [comment]
I think that a good option would be to use a JSON format for the input file, I have seen that there are other options such as YAML. However, I think that for our purpose, JSON would work fine. 

The JSON file should have all the needed parameters in the following form, which is a format somehow confortable for us:

```
{
  "sample": "sample.dat",
  "initial_state": "initial_state.dat",
  "kb": 8.6173e-2,
  "field": {start: 1.0, final:-1.0, cycle:True, num_points:100},
  "gyromagnetic_ratio": 1.760e11,
  "num_iterations": 1e4,
  "damping": 1.0,
  "seed": 9875,
  "deltat": 1e-15,
  "temperature": 1.0,
  "skipping": 50, 
  "out": "results.h5"
}
```
Regarding the sample input file, each row of the file should have the index and magnitude spin moment of the site along with their neighbors indexes and the exchange interaction constant between the given index and its given neighbor's indexes. This parameters can be considered as a list for every index_site of the same length as that of the neighbors_indexes list. At the end of the row, the type of the index_site. For example, for a given row, the sample file would look like:

```
index_site mag_spin_moment[index_site] *(neighbors_indexes[index_site]) *(J_exchange[index_site]) *(field[index_site]) *(anisotropy[index_site]) type
```

with anisotropy[index_site] and field[index_site] being something like

```
anisotropy[index_site] = [0.0 0.0 1.0 kan[index_site]]
field[index_site] = [0.0 0.0 1.0 field[index_site]]
```

In that way, the number of sites can be determined by counting the number of rows of the sample file. Regarding the several arguments of the spin_field and external_field fortran functions, all of them can be computed from that sample input file for a given row and the remaining ones can be obtained from the JSON input file.

For the output file I think that it is worthy to consider a Hierarchical Data Format, given the large amount of data we will be dealing with. I think it would be good to obtain the state of the magnetic moments at each iteration, or by using customized skipping quantity which is defined in the JSON input file.
