### ISSUE TITLE
Implement cubic anisotropy term

### ISSUE THREAD

**Issue by jussalcedoga** [jdalzatec/llg#61]
I think that implementing a cubic anisotropy term it is worth it, I don't know what you guys think.
<img src="https://latex.codecogs.com/png.latex?%5Cmathcal%7BH%7D_%7B%5Ctext%7Bani%7D%7D%5E%7B%5Ctext%7Bcub%7D%7D%20%3D%20%5Cfrac%7Bk_c%7D%7B2%7D%5Cdisplaystyle%5Csum_i%28S_x%5E4%20&plus;%20S_y%5E4%20&plus;%20S_z%20%5E4%29"/>

With this in mind, the effective field term would be:

<img src="https://latex.codecogs.com/png.latex?%5Cfrac%7B%5Cpartial%20%5Cmathcal%7BH_%7B%5Ctext%7Bani%7D%7D%5E%7B%5Ctext%7Bcub%7D%7D%7D%7D%7B%5Cpartial%20%5Cboldsymbol%20S_%7Bi%7D%7D%20%3D%202k_c%5Cdisplaystyle%20%5Csum_i%20%28S_x%5E3&plus;S_y%5E3&plus;S_z%5E3%29"/>

**Comment by jdalzatec** [comment]
First of all, I am not pretty sure your proposal for the spin field is correct. I think it is a bit tricky it seems. You could revise [this link](http://www.iue.tuwien.ac.at/phd/makarov/dissertationch5.html) where the fields are proposed as well as a lot of references for documentation. It is worthy to say that equations apply for micro-scale. However, it should be possible to apply them to the atomistic way with the right considerations.

Finally, I think it could be a good proposal for a future version. Right now, there are other issues we should face. I propose to focus on the main things and consider these features for the future. In this way, we could close this issue.

Sign:
- [ ] @jdalzatec 
- [ ] @lufvelasquezgo 
- [ ] @dfrodriguezp 
- [ ] @jussalcedoga
