### ISSUE TITLE
Question about Heun integration scheme

### ISSUE THREAD

**Issue by dfrodriguezp** [jdalzatec/llg#67]
I found the following text in an [article](https://iopscience.iop.org/article/10.1088/0953-8984/26/10/103202)

> The predictor step of the integration is performed on every spin in the system before proceeding to evaluate the corrector step for every spin. -Evans _et al._ (page 8)

This is very different to the implementation that we currently have, since we are applying the predictor _and_ the corrector step on every site one by one.

I would like to discuss this with you if you agree

Sign:

- [x] @dfrodriguezp 
- [x] @jussalcedoga 
- [x] @jdalzatec 
- [ ] @lufvelasquezgo

**Comment by jdalzatec** [comment]
[I think we are doing well](https://github.com/jdalzatec/llg/blob/master/fortran-src/heun.f90).
